name: HotPotato
version: 1.0.0
author: Azox
main: net.azox.hotpotato.HotPotato
api-version: 1.21
description: A dangerous hot potato plugin

commands:
  hotpotato:
    description: HotPotato main command
    usage: /hotpotato <trigger|check>
    permission: hotpotato.admin
  hpt:
    description: HotPotato alias command
    usage: /hpt <trigger|check>
    permission: hotpotato.admin